apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-myapp-cert
  namespace: myapp
spec:
  dnsNames:
    - myapp.kbaenak.tech
  secretName: tls-cert
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
