apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-myapp-cert
  namespace: myapp
spec:
  dnsNames:
    - web5.kbaenak.tech
  secretName: app-tls
  issuerRef:
    name: letsencrypt-prod-myapp
    kind: ClusterIssuer
